/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface MeasurementsSimulatedGet$Params {
  measurementFrequencyHz?: (number | string);
  signal?: string;
  signalFrequencyHz?: (number | string);
  variationPercent?: (number | string);
}

export function measurementsSimulatedGet(http: HttpClient, rootUrl: string, params?: MeasurementsSimulatedGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, measurementsSimulatedGet.PATH, 'get');
  if (params) {
    rb.query('measurementFrequencyHz', params.measurementFrequencyHz, {});
    rb.query('signal', params.signal, {});
    rb.query('signalFrequencyHz', params.signalFrequencyHz, {});
    rb.query('variationPercent', params.variationPercent, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

measurementsSimulatedGet.PATH = '/measurements/simulated';
